---
title: "Contact"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(icons)
```

<style type="text/css">
.title {
  display: none;
}

</style>
<div class = "header">

## **Zachary M. Moore**
Ontario, Canada

e-mail: zacharymilosmoore@gmail.com

[iNaturalist](https://inaturalist.ca/people/zacharymilosmoore) |
[eBird](https://ebird.org/profile/MTYwMzc5NQ/world)

```{r echo = F}
icon_style(fontawesome$brands$github,scale=5)
```
[GitHub](https://www.github.com/zacharymilosmoore)
   
```{r echo = F}
icon_style(fontawesome$brands$linkedin,scale=5,colour="blue")
```
[LinkedIn](https://www.linkedin.com/in/zacharymilosmoore)

```{r echo = F}
icon_style(fontawesome$brands$researchgate,scale=5)
```
[Research Gate](https://www.researchgate.net/profile/Zachary-Moore-18)
    
```{r echo = F}
icon_style(simple_icons$fiverr,scale=5)
```
[fiverr](https://www.fiverr.com/zacharymmoore)
    
```{r echo = F}
icon_style(simple_icons$upwork,scale=5)
```
[UpWork](https://www.upwork.com/freelancers/~019740478890543483)


</div>
<div class="header">

Last Updated: 
```{r,results="asis",echo=F} 

cat(format(Sys.time(),"%c"))
```
[GitHub Source](https://github.com/zacharymilosmoore/zacharymilosmoore.github.io)
</div>
