---
title: "**CV**"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: true
    toc_depth: 1

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(jsonlite)
library(tidyverse)
library(glue)

```


```{r, echo=FALSE,results="asis"}

cv<-read_excel("cv_zmm.xlsx",sheet="CV")
categories<-c("Education","Employment","Projects")

for (c in categories){
  cv_sub<-subset(cv,Category==c & CV=="Include")
  
  cat("#"," **", c, "** ", "\n",sep="")
  
  for (i in 1:nrow(cv_sub)){
    entry<-cv_sub[i,]
      start<-as.character(paste(entry$Start_Month,"-",entry$Start_Year,sep=""))
      end<-as.character(paste(entry$End_Month,"-",entry$End_Year,sep=""))
      timing<-as.character(paste(start," to ",end,sep=""))
      
      description<-paste(
        "**",entry$Title,"**", "\n","\n",
        entry$Description, "\n","\n",
        ifelse(is.na(entry$Tasks)==T,"",paste(entry$Tasks,"\n","\n")),
        ifelse(is.na(entry$Achievements)==T,"",paste(entry$Achievements,"\n","\n")),
        ifelse(is.na(entry$Lessons)==T,"",paste(entry$Lessons,"\n","\n")),sep="")
        
      
      org<-if(is.na(entry$Org_Acr)==T) {entry$Organization} else {
        paste(entry$Organization, " (", entry$Org_Acr,")",sep="")}
      
      org.link<-if(is.na(entry$Org_Link)==T) {"No Website Available"} else {
        paste("[",org,"]","(",entry$Org_Link,")",sep="")}
      
      V1<-paste(
        ifelse(is.na(entry$V1)==T,"",
               paste("![",entry$V1_Desc,"]","(visuals/",entry$V1,entry$V1_Type,")",sep="")),sep="")
      V2<-paste(
        ifelse(is.na(entry$V2)==T,"",
               paste("![",entry$V2_Desc,"]","(visuals/",entry$V2,entry$V2_Type,")",sep="")),sep="")
      V3<-paste(
        ifelse(is.na(entry$V3)==T,"",
               paste("![",entry$V3_Desc,"]","(visuals/",entry$V3,entry$V3_Type,")",sep="")),sep="")
      
      L1<-paste(
        ifelse(is.na(entry$L1)==T,"No Website Available",
               paste("[",entry$L1_Desc,"](",entry$L1,")",sep="")),sep="")
      L2<-paste(
        ifelse(is.na(entry$L2)==T,"",
               paste("[",entry$L2_Desc,"](",entry$L2,")",sep="")),sep="")
      L3<-paste(
        ifelse(is.na(entry$L3)==T,"",
               paste("[",entry$L3_Desc,"](",entry$L3,")",sep="")),sep="")
      
    cat("##", (if(c=="Projects"){entry$Title} else {entry$Organization}), 
        "{.tabset}", "\n","\n")

    cat("###", timing,"\n","\n")
    cat("###", org,"\n","\n")
        cat(org.link,"\n","\n")

    cat("###", "Description", "\n","\n")
      cat(description, "\n","\n")
      

    cat("###", "Visuals", "\n", "\n")
      cat(V1,V2,V3,"\n","\n")
      
    cat("###", "Links", "\n", "\n")
      cat(L1,L2,L3,"\n","\n")
  }
  cat("\n")
}

```

</div>
<div class="header-card">
Last Updated: 
```{r,results="asis",echo=F} 

cat(format(Sys.time(),"%c"))
```
</div>

